openapi: 3.0.0
info:
  version: 1.1.0
  title: Zenduty Account Custom Role Global Router Rules API
  termsOfService: https://zenduty.com
  contact:
    email: vishwa@zenduty.com
  license:
    name: Apache 2.0
  x-logo:
    url: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOS4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9Ii05OC4zIDE3My43IDIwNi4zIDUzLjIiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgLTk4LjMgMTczLjcgMjA2LjMgNTMuMjsiIHhtbDpzcGFjZT0icHJlc2VydmUiPg0KPHN0eWxlIHR5cGU9InRleHQvY3NzIj4NCgkuc3Qwe2ZpbGw6IzBGMTcyQTt9DQoJLnN0MXtmaWxsOiNGRDlBMDA7fQ0KPC9zdHlsZT4NCjxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0tMjksMjEwLjJoNi4zYzIuNywwLDQuOSwyLjIsNC45LDQuOWgtMTguMWMwLTUuMyw0LjEtOS40LDcuOS0xMy4xbDMuOC0zLjdoLTcuMWMtMi41LDAtNC42LTIuMS00LjYtNC42aDE4DQoJYzAsNS4zLTQuMSw5LjQtNy44LDEzLjJMLTI5LDIxMC4yeiIvPg0KPHBhdGggY2xhc3M9InN0MCIgZD0iTTMuNywyMDUuOGgtMTUuNWMwLjEsMS41LDAuNiwyLjcsMS42LDMuNmMwLjksMC45LDIuMSwxLjIsMy41LDEuMmMyLDAsMy40LTAuOSw0LjMtMi41aDUuOA0KCWMtMC42LDItMS44LDMuNi0zLjUsNC45Yy0xLjgsMS4yLTMuOSwyLTYuNCwyYy0yLDAtMy45LTAuNS01LjUtMS40Yy0xLjYtMC45LTIuOS0yLjEtMy44LTMuN2MtMC45LTEuNi0xLjQtMy40LTEuNC01LjcNCgljMC0yLjEsMC41LTQuMSwxLjQtNS43YzAuOS0xLjYsMi4xLTIuOCwzLjgtMy43YzEuNi0wLjksMy40LTEuNCw1LjUtMS40YzIsMCwzLjgsMC40LDUuNCwxLjJjMS42LDAuOSwyLjgsMi4xLDMuNywzLjYNCgljMC45LDEuNiwxLjMsMy4zLDEuMyw1LjRDMy44LDIwNC42LDMuOCwyMDUuMiwzLjcsMjA1Ljh6IE0tMS43LDIwMi4yYzAtMS40LTAuNS0yLjUtMS41LTMuMmMtMS0wLjktMi4xLTEuMi0zLjUtMS4yDQoJYy0xLjQsMC0yLjQsMC40LTMuNCwxLjJjLTAuOSwwLjctMS41LDEuOC0xLjYsMy4zaDEwLjFWMjAyLjJ6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNMjcuOSwxOTguNGMwLjktMS42LDItMi45LDMuNS0zLjhjMS41LTAuOSwzLjEtMS40LDQuOS0xLjRjMS40LDAsMi42LDAuMywzLjksMC45YzEuMywwLjYsMi4zLDEuNCwzLDIuNHYtMTYuNw0KCWg1LjR2MzVoLTUuNHYtMy4xYy0wLjYsMS0xLjYsMS45LTIuOCwyLjVjLTEuMywwLjYtMi42LDEtNC4yLDFjLTEuOCwwLTMuNC0wLjUtNC45LTEuNGMtMS41LTAuOS0yLjYtMi4zLTMuNS0zLjkNCgljLTAuOS0xLjYtMS4zLTMuNS0xLjMtNS44QzI2LjYsMjAyLDI3LDIwMCwyNy45LDE5OC40eiBNNDIuNSwyMDAuOWMtMC41LTAuOS0xLjMtMS42LTItMi4xYy0wLjktMC41LTEuOC0wLjgtMi44LTAuOA0KCWMtMSwwLTEuOSwwLjMtMi44LDAuOGMtMC45LDAuNS0xLjUsMS4xLTIsMi4xYy0wLjUsMC45LTAuOCwyLTAuOCwzLjNjMCwxLjMsMC4zLDIuNCwwLjgsMy40YzAuNSwxLDEuMywxLjYsMiwyLjENCgljMC45LDAuNSwxLjgsMC44LDIuOCwwLjhjMSwwLDEuOS0wLjMsMi44LTAuOGMwLjktMC41LDEuNS0xLjMsMi0yLjFjMC41LTAuOSwwLjgtMiwwLjgtMy40UzQzLDIwMS44LDQyLjUsMjAwLjl6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNMjUuNCwyMDQuM3YxMC42aC01di0xMC42YzAtMi0wLjUtMy41LTEuNS00LjVjLTEtMS4xLTIuMS0xLjYtMy41LTEuNnMtMi41LDAuNS0zLjUsMS42DQoJYy0wLjksMS0xLjQsMi42LTEuNCw0LjV2MTAuNkg1LjV2LTEwLjZjMC0yLjEsMC41LTQsMS4zLTUuN2MwLjktMS42LDItMi45LDMuNS0zLjhzMy4xLTEuNCw1LTEuNHMzLjUsMC41LDUsMS40DQoJYzEuNSwwLjksMi42LDIuMSwzLjUsMy44QzI0LjksMjAwLjMsMjUuNCwyMDIuMiwyNS40LDIwNC4zeiIvPg0KPHBhdGggY2xhc3M9InN0MCIgZD0iTTUxLjMsMjA0LjF2LTEwLjRoNXYxMC40YzAsMiwwLjUsMy41LDEuNSw0LjVjMSwxLjEsMi4xLDEuNiwzLjUsMS42YzEuNCwwLDIuNS0wLjUsMy41LTEuNg0KCWMwLjktMSwxLjQtMi42LDEuNC00LjV2LTEwLjRoNC45djEwLjRjMCwyLjEtMC41LDQtMS4zLDUuN2MtMC45LDEuNi0yLDIuOS0zLjUsMy44Yy0xLjUsMC45LTMuMSwxLjQtNSwxLjRzLTMuNS0wLjUtNS0xLjQNCgljLTEuNS0wLjktMi42LTIuMS0zLjUtMy44QzUxLjcsMjA4LjEsNTEuMywyMDYuMiw1MS4zLDIwNC4xeiIvPg0KPHBhdGggY2xhc3M9InN0MCIgZD0iTTgwLjcsMTk4djEwLjJjMCwwLjgsMC4xLDEuMywwLjUsMS41YzAuNCwwLjQsMC45LDAuNSwxLjgsMC41aDIuNXY0LjVoLTMuNGMtNC41LDAtNi44LTIuMS02LjgtNi41VjE5OGgtNS4xDQoJdi00LjRoNS4xdi04LjdoNS40djguN2g0LjhsMi42LDQuNEg4MC43eiIvPg0KPHBhdGggY2xhc3M9InN0MCIgZD0iTTEwNy40LDE5My42bC04LjcsMjAuNmwtNSwxMS44aC01LjdsNS4xLTExLjhsLTguNC0yMC42aDZsNS40LDE0LjdsNS41LTE0LjdIMTA3LjR6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNLTY2LjksMTg5LjJjLTEuOSwwLTQuNy0yLjEtNC43LTQuOHYtMy42YzAtMi43LDAuOC00LjgsNC43LTQuOGMzLjksMCw0LjcsMi4xLDQuNyw0Ljh2My42DQoJQy02Mi4yLDE4Ny4xLTY1LDE4OS4yLTY2LjksMTg5LjJ6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNLTM3LjcsMjIzaC0yMS41bDMuOC0xMS40bDAuNy0xLjhjNC4yLDEuNywxMy4xLDcuMiwxNy43LDExLjZDLTM2LjQsMjIyLjEtMzYuOCwyMjMtMzcuNywyMjN6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNLTU3LjMsMTkyLjlsLTE1LjksMTAuNGMtNC4yLTIuNS05LjItNS45LTEyLjItOC44Yy0wLjYtMC42LTAuMi0xLjUsMC43LTEuNUgtNTcuM3oiLz4NCjxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik0tNDguNiwxOTQuM2wtNiwxNS42bC0wLjcsMS44bC0zLjgsMTEuNEgtOTZjLTAuOCwwLTEuMy0wLjktMC44LTEuNWMwLjktMS4yLDEuOC0yLjMsMi43LTMuMw0KCWMyLjEtMi4yLDQuNC00LjEsNi45LTUuOGwwLjEtMC4xYzAuOC0wLjYsMS42LTEuMSwyLjQtMS42bDExLjQtNy40bDE1LjktMTAuNGg3LjdDLTQ4LjgsMTkyLjktNDguNCwxOTMuNi00OC42LDE5NC4zeiIvPg0KPC9zdmc+DQo=
  description: "# Introduction\n\nZenduty is a cutting edge platform for incident management. With high level automation, Zenduty enables faster and better incident resolution keeping developers first.\n\n\n  Javascript Libraries: https://github.com/Zenduty/zenduty-js\n\n  Ruby Libraries: https://github.com/Zenduty/zenduty-ruby\n\n  Python Libraries: https://github.com/Zenduty/zenduty-python-sdk\n\n  Postman Collection for Zenduty API: https://github.com/Zenduty/zenduty-api-postman.git\n\n  Account-level roles and permissions: https://docs.zenduty.com/docs/users#account-level-roles-and-permissions\n\n  Team-level roles and permissions: https://docs.zenduty.com/docs/users#team-level-roles-and-permissions\n"
servers:
- url: https://www.zenduty.com
security:
- bearerAuth: []
tags:
- name: Global Router Rules
  description: The Rules of the Global Router in an Account are represented by this object. Visit this link to view the documentation for the global alert routing rules https://docs.zenduty.com/docs/globalalertrouting
paths:
  /api/v2/account/events/router/{router_id}/rulesets/:
    parameters:
    - name: router_id
      in: path
      description: unique_id of the Global Router object
      schema:
        type: string
      required: true
    post:
      tags:
      - Global Router Rules
      summary: Create the Global Router Rule object
      description: Create the Global Router Rule object by setting the values of all the required parameters passed in the request body.
      requestBody:
        description: Request body parameters to create the Global Router Rule object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GlobalRouterRulePayload'
            example:
              name: Rule for Grafana Integration
              actions:
              - action_type: 0
                integration: 0c4e939d-6d54-401e-ad83-6114368bdd0b
              rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"898aa9ba-0123-4456-b89a-b16a429f5d94":{"type":"rule","id":"898aa9ba-0123-4456-b89a-b16a429f5d94","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.commonLabels.alertname","grafana"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","898aa9ba-0123-4456-b89a-b16a429f5d94"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
          application/xml:
            schema:
              $ref: '#/components/schemas/GlobalRouterRulePayload'
            example:
              name: Rule for Grafana Integration
              actions:
              - action_type: 0
                integration: 0c4e939d-6d54-401e-ad83-6114368bdd0b
              rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"898aa9ba-0123-4456-b89a-b16a429f5d94":{"type":"rule","id":"898aa9ba-0123-4456-b89a-b16a429f5d94","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.commonLabels.alertname","grafana"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","898aa9ba-0123-4456-b89a-b16a429f5d94"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalRouterRule'
              example:
                unique_id: 4c9924cc-d051-4e58-978b-d673a7de540a
                name: Rule for Grafana Integration
                position: 7
                rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"898aa9ba-0123-4456-b89a-b16a429f5d94":{"type":"rule","id":"898aa9ba-0123-4456-b89a-b16a429f5d94","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.commonLabels.alertname","grafana"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","898aa9ba-0123-4456-b89a-b16a429f5d94"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
                actions:
                - unique_id: fb742645-dc2f-4b76-bf44-8a0a8aa48e09
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                router: e9be034e-6076-4953-a315-9a3666ffe774
            application/xml:
              schema:
                $ref: '#/components/schemas/GlobalRouterRule'
              example:
                unique_id: b0c1867f-dfd2-4cb3-a298-0b9f322fe716
                name: Infra Global Router
                description: This is Infra Global Router for this account
                account: 61fb2d9e-088b-471f-a6d7-872c03cf483d
                is_enabled: true
                integration_key: cb1de2f2-bb17-4a6c-8a80-03739ca0a911
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
    get:
      tags:
      - Global Router Rules
      summary: List all Global Router Rule objects
      description: Returns a list of Global Router Rule objects.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalRouterRule'
              example:
              - unique_id: 12edd6c5-2217-4b53-b635-83083f420dd8
                name: position 1
                position: 1
                rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"8bbbbaba-cdef-4012-b456-7184d20607aa":{"type":"rule","id":"8bbbbaba-cdef-4012-b456-7184d20607aa","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.payload.summary","testing"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","8bbbbaba-cdef-4012-b456-7184d20607aa"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
                actions:
                - unique_id: 6d90b452-6b5f-4ea1-8b58-9ad091aba040
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                - unique_id: be64664d-ab1d-419a-ab50-d48b05cbc1e6
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                router: e9be034e-6076-4953-a315-9a3666ffe774
              - unique_id: 4c9924cc-d051-4e58-978b-d673a7de540a
                name: Rule for Grafana Integration
                position: 2
                rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"898aa9ba-0123-4456-b89a-b16a429f5d94":{"type":"rule","id":"898aa9ba-0123-4456-b89a-b16a429f5d94","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.commonLabels.alertname","grafana"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","898aa9ba-0123-4456-b89a-b16a429f5d94"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
                actions:
                - unique_id: fb742645-dc2f-4b76-bf44-8a0a8aa48e09
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                router: e9be034e-6076-4953-a315-9a3666ffe774
            application/xml:
              schema:
                $ref: '#/components/schemas/GlobalRouterRule'
              example:
              - unique_id: 12edd6c5-2217-4b53-b635-83083f420dd8
                name: position 1
                position: 1
                rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"8bbbbaba-cdef-4012-b456-7184d20607aa":{"type":"rule","id":"8bbbbaba-cdef-4012-b456-7184d20607aa","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.payload.summary","testing"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","8bbbbaba-cdef-4012-b456-7184d20607aa"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
                actions:
                - unique_id: 6d90b452-6b5f-4ea1-8b58-9ad091aba040
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                - unique_id: be64664d-ab1d-419a-ab50-d48b05cbc1e6
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                router: e9be034e-6076-4953-a315-9a3666ffe774
              - unique_id: 4c9924cc-d051-4e58-978b-d673a7de540a
                name: Rule for Grafana Integration
                position: 2
                rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"898aa9ba-0123-4456-b89a-b16a429f5d94":{"type":"rule","id":"898aa9ba-0123-4456-b89a-b16a429f5d94","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.commonLabels.alertname","grafana"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","898aa9ba-0123-4456-b89a-b16a429f5d94"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
                actions:
                - unique_id: fb742645-dc2f-4b76-bf44-8a0a8aa48e09
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                router: e9be034e-6076-4953-a315-9a3666ffe774
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
    put:
      tags:
      - Global Router Rules
      summary: Update the Global Router Rule object
      description: Updates the position of the Global Router Rule object by setting the position and rule unique id passed in the request body
      requestBody:
        description: Request body parameters to update the position of Global Router Rule object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GlobalRouterRulePositionPayload'
            example:
              rule: 12edd6c5-2217-4b53-b635-83083f420dd8
              position: 1
          application/xml:
            schema:
              $ref: '#/components/schemas/GlobalRouterRulePositionPayload'
            example:
              rule: 12edd6c5-2217-4b53-b635-83083f420dd8
              position: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalRouterRule'
              example:
              - unique_id: 12edd6c5-2217-4b53-b635-83083f420dd8
                name: position 1
                position: 1
                rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"8bbbbaba-cdef-4012-b456-7184d20607aa":{"type":"rule","id":"8bbbbaba-cdef-4012-b456-7184d20607aa","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.payload.summary","testing"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","8bbbbaba-cdef-4012-b456-7184d20607aa"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
                actions:
                - unique_id: 6d90b452-6b5f-4ea1-8b58-9ad091aba040
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                - unique_id: be64664d-ab1d-419a-ab50-d48b05cbc1e6
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                router: e9be034e-6076-4953-a315-9a3666ffe774
              - unique_id: c757e713-e2c4-40f1-813a-6c82b487d9b2
                name: position 2
                position: 2
                rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"8bbbbaba-cdef-4012-b456-7184d20607aa":{"type":"rule","id":"8bbbbaba-cdef-4012-b456-7184d20607aa","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.payload.summary","testing"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","8bbbbaba-cdef-4012-b456-7184d20607aa"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
                actions:
                - unique_id: 69efe5d0-450e-4842-98ce-2bd4235ed4f7
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                - unique_id: ca20dc3c-bbd8-467d-8aba-ad50547858c2
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                router: e9be034e-6076-4953-a315-9a3666ffe774
            application/xml:
              schema:
                $ref: '#/components/schemas/GlobalRouterRule'
              example:
              - unique_id: 12edd6c5-2217-4b53-b635-83083f420dd8
                name: position 1
                position: 1
                rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"8bbbbaba-cdef-4012-b456-7184d20607aa":{"type":"rule","id":"8bbbbaba-cdef-4012-b456-7184d20607aa","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.payload.summary","testing"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","8bbbbaba-cdef-4012-b456-7184d20607aa"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
                actions:
                - unique_id: 6d90b452-6b5f-4ea1-8b58-9ad091aba040
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                - unique_id: be64664d-ab1d-419a-ab50-d48b05cbc1e6
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                router: e9be034e-6076-4953-a315-9a3666ffe774
              - unique_id: c757e713-e2c4-40f1-813a-6c82b487d9b2
                name: position 2
                position: 2
                rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"8bbbbaba-cdef-4012-b456-7184d20607aa":{"type":"rule","id":"8bbbbaba-cdef-4012-b456-7184d20607aa","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.payload.summary","testing"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","8bbbbaba-cdef-4012-b456-7184d20607aa"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
                actions:
                - unique_id: 69efe5d0-450e-4842-98ce-2bd4235ed4f7
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                - unique_id: ca20dc3c-bbd8-467d-8aba-ad50547858c2
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                router: e9be034e-6076-4953-a315-9a3666ffe774
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
  /api/v2/account/events/router/{router_id}/rulesets/{ruleset_id}/:
    parameters:
    - name: router_id
      in: path
      description: unique_id of the Global Router object
      schema:
        type: string
      required: true
    - name: ruleset_id
      in: path
      description: unique_id of the Global Router Rule object
      schema:
        type: string
      required: true
    get:
      tags:
      - Global Router Rules
      summary: Retrieve the Global Router Rule object
      description: Retrieve the specified Global Router Rule object.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalRouterRule'
              example:
                unique_id: 4c9924cc-d051-4e58-978b-d673a7de540a
                name: Rule for Grafana Integration
                position: 2
                rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"898aa9ba-0123-4456-b89a-b16a429f5d94":{"type":"rule","id":"898aa9ba-0123-4456-b89a-b16a429f5d94","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.commonLabels.alertname","grafana"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","898aa9ba-0123-4456-b89a-b16a429f5d94"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
                actions:
                - unique_id: fb742645-dc2f-4b76-bf44-8a0a8aa48e09
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                router: e9be034e-6076-4953-a315-9a3666ffe774
            application/xml:
              schema:
                $ref: '#/components/schemas/GlobalRouterRule'
              example:
                unique_id: 4c9924cc-d051-4e58-978b-d673a7de540a
                name: Rule for Grafana Integration
                position: 2
                rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"898aa9ba-0123-4456-b89a-b16a429f5d94":{"type":"rule","id":"898aa9ba-0123-4456-b89a-b16a429f5d94","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.commonLabels.alertname","grafana"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","898aa9ba-0123-4456-b89a-b16a429f5d94"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
                actions:
                - unique_id: fb742645-dc2f-4b76-bf44-8a0a8aa48e09
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                router: e9be034e-6076-4953-a315-9a3666ffe774
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
    put:
      tags:
      - Global Router Rules
      summary: Update the Global Router Rule data
      description: Updates the specified Global Router Rule object by setting the values of the parameters passed in the request body. Any parameters not provided will be left unchanged.
      requestBody:
        description: Request body parameters to update the Global Router Rule object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GlobalRouterRulePayload'
            example:
              name: Rule for Grafana Integration Updated
              rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"898aa9ba-0123-4456-b89a-b16a429f5d94":{"type":"rule","id":"898aa9ba-0123-4456-b89a-b16a429f5d94","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.commonLabels.alertname","grafana"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","898aa9ba-0123-4456-b89a-b16a429f5d94"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
              actions:
              - action_type: 0
                integration: 0c4e939d-6d54-401e-ad83-6114368bdd0b
          application/xml:
            schema:
              $ref: '#/components/schemas/GlobalRouterRulePayload'
            example:
              name: Rule for Grafana Integration Updated
              rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"898aa9ba-0123-4456-b89a-b16a429f5d94":{"type":"rule","id":"898aa9ba-0123-4456-b89a-b16a429f5d94","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.commonLabels.alertname","grafana"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","898aa9ba-0123-4456-b89a-b16a429f5d94"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
              actions:
              - action_type: 0
                integration: 0c4e939d-6d54-401e-ad83-6114368bdd0b
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalRouterRule'
              example:
                unique_id: 4c9924cc-d051-4e58-978b-d673a7de540a
                name: Rule for Grafana Integration Updated
                position: 2
                rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"898aa9ba-0123-4456-b89a-b16a429f5d94":{"type":"rule","id":"898aa9ba-0123-4456-b89a-b16a429f5d94","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.commonLabels.alertname","grafana"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","898aa9ba-0123-4456-b89a-b16a429f5d94"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
                actions:
                - unique_id: d926e67a-60ae-4ed4-8ece-b93c31da6bc7
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                router: e9be034e-6076-4953-a315-9a3666ffe774
            application/xml:
              schema:
                $ref: '#/components/schemas/GlobalRouterRule'
              example:
                unique_id: 4c9924cc-d051-4e58-978b-d673a7de540a
                name: Rule for Grafana Integration Updated
                position: 2
                rule_json: '{"type":"group","id":"9a99988a-0123-4456-b89a-b1607f326fd8","children1":{"898aa9ba-0123-4456-b89a-b16a429f5d94":{"type":"rule","id":"898aa9ba-0123-4456-b89a-b16a429f5d94","properties":{"field":"alert.payload","operator":"payloadsearch","value":["$.commonLabels.alertname","grafana"],"valueSrc":["value","value"],"operatorOptions":{"ploperator":"equal"},"valueType":["text","text"]},"path":["9a99988a-0123-4456-b89a-b1607f326fd8","898aa9ba-0123-4456-b89a-b16a429f5d94"]}},"properties":{"conjunction":"AND","not":false},"path":["9a99988a-0123-4456-b89a-b1607f326fd8"]}'
                actions:
                - unique_id: d926e67a-60ae-4ed4-8ece-b93c31da6bc7
                  action_type: 0
                  service:
                    name: Team 1 Service 1
                    unique_id: 32a7c77f-aa0a-49de-ab52-e52f0aa77888
                  team:
                    name: Team 1
                    unique_id: 91fd3cc0-ebd6-43b8-aab3-67a05762ba0c
                  integration_obj:
                    unique_id: 0c4e939d-6d54-401e-ad83-6114368bdd0b
                    name: Anodot
                router: e9be034e-6076-4953-a315-9a3666ffe774
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
    delete:
      tags:
      - Global Router Rules
      summary: Delete the Global Router Rule data
      description: Delete the specified Global Router Rule object permanently.
      responses:
        '204':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
components:
  schemas:
    GlobalRouterRule:
      description: Global Router Rule object schema
      type: object
      properties:
        unique_id:
          type: string
          description: A system-generated string that represents the Global Router Rule object's unique_id
        name:
          type: string
          description: A string that represents the Global Router Rule object's name
        position:
          type: integer
          description: An integer that represents the Global Router Rule object's position
        rule_json:
          type: string
          description: A string that represents the rule json of Global Router Rule object
        actions:
          type: array
          description: An array of Global Router Rule Action objects
          items:
            $ref: '#/components/schemas/GlobalRouterRuleAction'
        router:
          type: string
          description: A system-generated string that represents the Global Router object's unique_id
    GlobalRouterRulePositionPayload:
      type: object
      description: Payload schema for the Global Router Rule position update object
      properties:
        rule:
          type: string
          description: A system generated string that represents the unique id of the Global Router Rule object
        position:
          type: integer
          description: An integer that represents that position of the Global Router Rule object
    GlobalRouterRulePayload:
      description: Payload schema for Global Router Rule object
      type: object
      properties:
        name:
          type: string
          description: A string that represents the Global Router Rule object's name
        rule_json:
          type: string
          description: A string that represents the rule json of Global Router Rule object
        actions:
          type: array
          description: An array of Global Router Rule Action objects
          items:
            $ref: '#/components/schemas/GlobalRouterRuleActionPayload'
    GlobalRouterRuleActionPayload:
      type: object
      description: Payload schema for Global Router Rule Action object
      properties:
        action_type:
          type: integer
          description: An integer that represents the action type of the Global Router Rule Action object
        integration:
          type: string
          description: A system generated string that represents the unique id of the integration object
    GlobalRouterRuleAction:
      type: object
      description: Global Router Rule Action object schema
      properties:
        unique_id:
          type: string
          description: A system generated string that represents the unique id of Global Router Rule object
        action_type:
          type: integer
          description: An integer that represents the action type of the Global Router Rule Action object
        service:
          type: object
          description: Service object for Global Router Rule Action object
          properties:
            name:
              type: string
              description: A string that represents name of the Service object
            unique_id:
              type: string
              description: A system generated string that represents the unique_id of the Service object
        team:
          type: object
          description: Team object for Global Router Rule Action object
          properties:
            name:
              type: string
              description: A string that represents name of the Team object
            unique_id:
              type: string
              description: A system generated string that represents the unique_id of the Team object
        integration_obj:
          type: object
          description: Integration object for Global Router Rule Action object
          properties:
            name:
              type: string
              description: A string that represents name of the Integration object
            unique_id:
              type: string
              description: A system generated string that represents the unique_id of the Integration object
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Token <api_key>
