openapi: 3.0.0
info:
  version: 1.1.0
  title: Zenduty Account Custom Role Teams API
  termsOfService: https://zenduty.com
  contact:
    email: vishwa@zenduty.com
  license:
    name: Apache 2.0
  x-logo:
    url: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOS4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9Ii05OC4zIDE3My43IDIwNi4zIDUzLjIiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgLTk4LjMgMTczLjcgMjA2LjMgNTMuMjsiIHhtbDpzcGFjZT0icHJlc2VydmUiPg0KPHN0eWxlIHR5cGU9InRleHQvY3NzIj4NCgkuc3Qwe2ZpbGw6IzBGMTcyQTt9DQoJLnN0MXtmaWxsOiNGRDlBMDA7fQ0KPC9zdHlsZT4NCjxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0tMjksMjEwLjJoNi4zYzIuNywwLDQuOSwyLjIsNC45LDQuOWgtMTguMWMwLTUuMyw0LjEtOS40LDcuOS0xMy4xbDMuOC0zLjdoLTcuMWMtMi41LDAtNC42LTIuMS00LjYtNC42aDE4DQoJYzAsNS4zLTQuMSw5LjQtNy44LDEzLjJMLTI5LDIxMC4yeiIvPg0KPHBhdGggY2xhc3M9InN0MCIgZD0iTTMuNywyMDUuOGgtMTUuNWMwLjEsMS41LDAuNiwyLjcsMS42LDMuNmMwLjksMC45LDIuMSwxLjIsMy41LDEuMmMyLDAsMy40LTAuOSw0LjMtMi41aDUuOA0KCWMtMC42LDItMS44LDMuNi0zLjUsNC45Yy0xLjgsMS4yLTMuOSwyLTYuNCwyYy0yLDAtMy45LTAuNS01LjUtMS40Yy0xLjYtMC45LTIuOS0yLjEtMy44LTMuN2MtMC45LTEuNi0xLjQtMy40LTEuNC01LjcNCgljMC0yLjEsMC41LTQuMSwxLjQtNS43YzAuOS0xLjYsMi4xLTIuOCwzLjgtMy43YzEuNi0wLjksMy40LTEuNCw1LjUtMS40YzIsMCwzLjgsMC40LDUuNCwxLjJjMS42LDAuOSwyLjgsMi4xLDMuNywzLjYNCgljMC45LDEuNiwxLjMsMy4zLDEuMyw1LjRDMy44LDIwNC42LDMuOCwyMDUuMiwzLjcsMjA1Ljh6IE0tMS43LDIwMi4yYzAtMS40LTAuNS0yLjUtMS41LTMuMmMtMS0wLjktMi4xLTEuMi0zLjUtMS4yDQoJYy0xLjQsMC0yLjQsMC40LTMuNCwxLjJjLTAuOSwwLjctMS41LDEuOC0xLjYsMy4zaDEwLjFWMjAyLjJ6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNMjcuOSwxOTguNGMwLjktMS42LDItMi45LDMuNS0zLjhjMS41LTAuOSwzLjEtMS40LDQuOS0xLjRjMS40LDAsMi42LDAuMywzLjksMC45YzEuMywwLjYsMi4zLDEuNCwzLDIuNHYtMTYuNw0KCWg1LjR2MzVoLTUuNHYtMy4xYy0wLjYsMS0xLjYsMS45LTIuOCwyLjVjLTEuMywwLjYtMi42LDEtNC4yLDFjLTEuOCwwLTMuNC0wLjUtNC45LTEuNGMtMS41LTAuOS0yLjYtMi4zLTMuNS0zLjkNCgljLTAuOS0xLjYtMS4zLTMuNS0xLjMtNS44QzI2LjYsMjAyLDI3LDIwMCwyNy45LDE5OC40eiBNNDIuNSwyMDAuOWMtMC41LTAuOS0xLjMtMS42LTItMi4xYy0wLjktMC41LTEuOC0wLjgtMi44LTAuOA0KCWMtMSwwLTEuOSwwLjMtMi44LDAuOGMtMC45LDAuNS0xLjUsMS4xLTIsMi4xYy0wLjUsMC45LTAuOCwyLTAuOCwzLjNjMCwxLjMsMC4zLDIuNCwwLjgsMy40YzAuNSwxLDEuMywxLjYsMiwyLjENCgljMC45LDAuNSwxLjgsMC44LDIuOCwwLjhjMSwwLDEuOS0wLjMsMi44LTAuOGMwLjktMC41LDEuNS0xLjMsMi0yLjFjMC41LTAuOSwwLjgtMiwwLjgtMy40UzQzLDIwMS44LDQyLjUsMjAwLjl6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNMjUuNCwyMDQuM3YxMC42aC01di0xMC42YzAtMi0wLjUtMy41LTEuNS00LjVjLTEtMS4xLTIuMS0xLjYtMy41LTEuNnMtMi41LDAuNS0zLjUsMS42DQoJYy0wLjksMS0xLjQsMi42LTEuNCw0LjV2MTAuNkg1LjV2LTEwLjZjMC0yLjEsMC41LTQsMS4zLTUuN2MwLjktMS42LDItMi45LDMuNS0zLjhzMy4xLTEuNCw1LTEuNHMzLjUsMC41LDUsMS40DQoJYzEuNSwwLjksMi42LDIuMSwzLjUsMy44QzI0LjksMjAwLjMsMjUuNCwyMDIuMiwyNS40LDIwNC4zeiIvPg0KPHBhdGggY2xhc3M9InN0MCIgZD0iTTUxLjMsMjA0LjF2LTEwLjRoNXYxMC40YzAsMiwwLjUsMy41LDEuNSw0LjVjMSwxLjEsMi4xLDEuNiwzLjUsMS42YzEuNCwwLDIuNS0wLjUsMy41LTEuNg0KCWMwLjktMSwxLjQtMi42LDEuNC00LjV2LTEwLjRoNC45djEwLjRjMCwyLjEtMC41LDQtMS4zLDUuN2MtMC45LDEuNi0yLDIuOS0zLjUsMy44Yy0xLjUsMC45LTMuMSwxLjQtNSwxLjRzLTMuNS0wLjUtNS0xLjQNCgljLTEuNS0wLjktMi42LTIuMS0zLjUtMy44QzUxLjcsMjA4LjEsNTEuMywyMDYuMiw1MS4zLDIwNC4xeiIvPg0KPHBhdGggY2xhc3M9InN0MCIgZD0iTTgwLjcsMTk4djEwLjJjMCwwLjgsMC4xLDEuMywwLjUsMS41YzAuNCwwLjQsMC45LDAuNSwxLjgsMC41aDIuNXY0LjVoLTMuNGMtNC41LDAtNi44LTIuMS02LjgtNi41VjE5OGgtNS4xDQoJdi00LjRoNS4xdi04LjdoNS40djguN2g0LjhsMi42LDQuNEg4MC43eiIvPg0KPHBhdGggY2xhc3M9InN0MCIgZD0iTTEwNy40LDE5My42bC04LjcsMjAuNmwtNSwxMS44aC01LjdsNS4xLTExLjhsLTguNC0yMC42aDZsNS40LDE0LjdsNS41LTE0LjdIMTA3LjR6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNLTY2LjksMTg5LjJjLTEuOSwwLTQuNy0yLjEtNC43LTQuOHYtMy42YzAtMi43LDAuOC00LjgsNC43LTQuOGMzLjksMCw0LjcsMi4xLDQuNyw0Ljh2My42DQoJQy02Mi4yLDE4Ny4xLTY1LDE4OS4yLTY2LjksMTg5LjJ6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNLTM3LjcsMjIzaC0yMS41bDMuOC0xMS40bDAuNy0xLjhjNC4yLDEuNywxMy4xLDcuMiwxNy43LDExLjZDLTM2LjQsMjIyLjEtMzYuOCwyMjMtMzcuNywyMjN6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNLTU3LjMsMTkyLjlsLTE1LjksMTAuNGMtNC4yLTIuNS05LjItNS45LTEyLjItOC44Yy0wLjYtMC42LTAuMi0xLjUsMC43LTEuNUgtNTcuM3oiLz4NCjxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik0tNDguNiwxOTQuM2wtNiwxNS42bC0wLjcsMS44bC0zLjgsMTEuNEgtOTZjLTAuOCwwLTEuMy0wLjktMC44LTEuNWMwLjktMS4yLDEuOC0yLjMsMi43LTMuMw0KCWMyLjEtMi4yLDQuNC00LjEsNi45LTUuOGwwLjEtMC4xYzAuOC0wLjYsMS42LTEuMSwyLjQtMS42bDExLjQtNy40bDE1LjktMTAuNGg3LjdDLTQ4LjgsMTkyLjktNDguNCwxOTMuNi00OC42LDE5NC4zeiIvPg0KPC9zdmc+DQo=
  description: "# Introduction\n\nZenduty is a cutting edge platform for incident management. With high level automation, Zenduty enables faster and better incident resolution keeping developers first.\n\n\n  Javascript Libraries: https://github.com/Zenduty/zenduty-js\n\n  Ruby Libraries: https://github.com/Zenduty/zenduty-ruby\n\n  Python Libraries: https://github.com/Zenduty/zenduty-python-sdk\n\n  Postman Collection for Zenduty API: https://github.com/Zenduty/zenduty-api-postman.git\n\n  Account-level roles and permissions: https://docs.zenduty.com/docs/users#account-level-roles-and-permissions\n\n  Team-level roles and permissions: https://docs.zenduty.com/docs/users#team-level-roles-and-permissions\n"
servers:
- url: https://www.zenduty.com
security:
- bearerAuth: []
tags:
- name: Teams
  description: This object represents a team of the account. It lets you create different independent operational units in the account. You can check out the team docs here https://docs.zenduty.com/docs/teams.
paths:
  /api/account/teams/:
    post:
      tags:
      - Teams
      summary: Create the Team object
      description: Create the Team object by setting the values of all the required parameters passed in the request body.
      requestBody:
        description: Request body parameters to create the Team object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamPayload'
            example:
              name: Production Team
          application/xml:
            schema:
              $ref: '#/components/schemas/TeamPayload'
            example:
              name: Production Team
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
              example:
                unique_id: 61010821-08aa-4098-94f8-f88f1990b54a
                name: Production Team
                account: 0713dc12-40b0-46ff-b0f9-c6b126399277
                creation_date: '2022-07-08'
                members:
                - unique_id: d916157c-ff8b-43be-8e99-4b63699fdf72
                  team: 61010821-08aa-4098-94f8-f88f1990b54a
                  user:
                    username: 216bba3d-7268-4a8e-89e9-6
                    first_name: Anshul
                    last_name: Rajput
                    email: anshulrajput229@gmail.com
                  joining_date: '2022-07-08T10:41:36.600148Z'
                  role: 1
                owner: 216bba3d-7268-4a8e-89e9-6
                roles:
                - unique_id: 89752b4a-43df-401d-9dc0-a446690a7a0e
                  team: 61010821-08aa-4098-94f8-f88f1990b54a
                  title: Incident Commander
                  description: The incident commander is the person responsible for all aspects of the incident response, including quickly developing incident objectives, managing all incident operations, application of resources as well as responsibility for all persons involved. The incident commander sets priorities and defines the organization of the incident response teams and the overall incident action plan.
                  creation_date: '2022-07-08T10:41:36.623257Z'
                  rank: 1
            application/xml:
              schema:
                $ref: '#/components/schemas/Team'
              example:
                unique_id: 61010821-08aa-4098-94f8-f88f1990b54a
                name: Production Team
                account: 0713dc12-40b0-46ff-b0f9-c6b126399277
                creation_date: '2022-07-08'
                members:
                - unique_id: d916157c-ff8b-43be-8e99-4b63699fdf72
                  team: 61010821-08aa-4098-94f8-f88f1990b54a
                  user:
                    username: 216bba3d-7268-4a8e-89e9-6
                    first_name: Anshul
                    last_name: Rajput
                    email: anshulrajput229@gmail.com
                  joining_date: '2022-07-08T10:41:36.600148Z'
                  role: 1
                owner: 216bba3d-7268-4a8e-89e9-6
                roles:
                - unique_id: 89752b4a-43df-401d-9dc0-a446690a7a0e
                  team: 61010821-08aa-4098-94f8-f88f1990b54a
                  title: Incident Commander
                  description: The incident commander is the person responsible for all aspects of the incident response, including quickly developing incident objectives, managing all incident operations, application of resources as well as responsibility for all persons involved. The incident commander sets priorities and defines the organization of the incident response teams and the overall incident action plan.
                  creation_date: '2022-07-08T10:41:36.623257Z'
                  rank: 1
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
    get:
      tags:
      - Teams
      summary: List all Team objects
      description: Returns a list of Team objects. The Team objects are sorted by creation_date, with the most recent Team object appearing last.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
              example:
              - unique_id: 1f1b4d79-ed32-44fc-926d-f794b975200c
                name: Operation Team
                account: 0713dc12-40b0-46ff-b0f9-c6b126399277
                creation_date: '2022-07-08'
                members:
                - unique_id: 90a97f10-d290-4bd0-9f83-525f130c6399
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  user:
                    username: 216bba3d-7268-4a8e-89e9-6
                    first_name: Anshul
                    last_name: Rajput
                    email: anshulrajput229@gmail.com
                  joining_date: '2022-07-08T10:29:36.408864Z'
                  role: 1
                - unique_id: 4af52265-b69e-4cd0-948a-fba33933588d
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  user:
                    username: 507dfda0-a1fd-40e5-943a-e
                    first_name: Mary
                    last_name: Jane
                    email: maryjane@sharklasers.com
                  joining_date: '2022-07-08T10:31:56.849950Z'
                  role: 2
                - unique_id: 76e76d20-2c82-49be-b987-244c8c6af57b
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  user:
                    username: 85b563c8-18d0-4668-9462-9
                    first_name: Vishwa
                    last_name: Krishnakumar
                    email: vishwa@yellowant.com
                  joining_date: '2022-07-08T10:32:42.213487Z'
                  role: 2
                owner: 216bba3d-7268-4a8e-89e9-6
                roles:
                - unique_id: ce2e4fec-7fb9-440c-b400-9a33639d8ba3
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  title: Incident Commander
                  description: The incident commander is the person responsible for all aspects of the incident response, including quickly developing incident objectives, managing all incident operations, application of resources as well as responsibility for all persons involved. The incident commander sets priorities and defines the organization of the incident response teams and the overall incident action plan.
                  creation_date: '2022-07-08T10:29:36.431801Z'
                  rank: 1
              - unique_id: 61010821-08aa-4098-94f8-f88f1990b54a
                name: Production Team
                account: 0713dc12-40b0-46ff-b0f9-c6b126399277
                creation_date: '2022-07-08'
                members:
                - unique_id: d916157c-ff8b-43be-8e99-4b63699fdf72
                  team: 61010821-08aa-4098-94f8-f88f1990b54a
                  user:
                    username: 216bba3d-7268-4a8e-89e9-6
                    first_name: Anshul
                    last_name: Rajput
                    email: anshulrajput229@gmail.com
                  joining_date: '2022-07-08T10:41:36.600148Z'
                  role: 1
                owner: 216bba3d-7268-4a8e-89e9-6
                roles:
                - unique_id: 89752b4a-43df-401d-9dc0-a446690a7a0e
                  team: 61010821-08aa-4098-94f8-f88f1990b54a
                  title: Incident Commander
                  description: The incident commander is the person responsible for all aspects of the incident response, including quickly developing incident objectives, managing all incident operations, application of resources as well as responsibility for all persons involved. The incident commander sets priorities and defines the organization of the incident response teams and the overall incident action plan.
                  creation_date: '2022-07-08T10:41:36.623257Z'
                  rank: 1
            application/xml:
              schema:
                $ref: '#/components/schemas/Team'
              example:
              - unique_id: 1f1b4d79-ed32-44fc-926d-f794b975200c
                name: Operation Team
                account: 0713dc12-40b0-46ff-b0f9-c6b126399277
                creation_date: '2022-07-08'
                members:
                - unique_id: 90a97f10-d290-4bd0-9f83-525f130c6399
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  user:
                    username: 216bba3d-7268-4a8e-89e9-6
                    first_name: Anshul
                    last_name: Rajput
                    email: anshulrajput229@gmail.com
                  joining_date: '2022-07-08T10:29:36.408864Z'
                  role: 1
                - unique_id: 4af52265-b69e-4cd0-948a-fba33933588d
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  user:
                    username: 507dfda0-a1fd-40e5-943a-e
                    first_name: Mary
                    last_name: Jane
                    email: maryjane@sharklasers.com
                  joining_date: '2022-07-08T10:31:56.849950Z'
                  role: 2
                - unique_id: 76e76d20-2c82-49be-b987-244c8c6af57b
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  user:
                    username: 85b563c8-18d0-4668-9462-9
                    first_name: Vishwa
                    last_name: Krishnakumar
                    email: vishwa@yellowant.com
                  joining_date: '2022-07-08T10:32:42.213487Z'
                  role: 2
                owner: 216bba3d-7268-4a8e-89e9-6
                roles:
                - unique_id: ce2e4fec-7fb9-440c-b400-9a33639d8ba3
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  title: Incident Commander
                  description: The incident commander is the person responsible for all aspects of the incident response, including quickly developing incident objectives, managing all incident operations, application of resources as well as responsibility for all persons involved. The incident commander sets priorities and defines the organization of the incident response teams and the overall incident action plan.
                  creation_date: '2022-07-08T10:29:36.431801Z'
                  rank: 1
              - unique_id: 61010821-08aa-4098-94f8-f88f1990b54a
                name: Production Team
                account: 0713dc12-40b0-46ff-b0f9-c6b126399277
                creation_date: '2022-07-08'
                members:
                - unique_id: d916157c-ff8b-43be-8e99-4b63699fdf72
                  team: 61010821-08aa-4098-94f8-f88f1990b54a
                  user:
                    username: 216bba3d-7268-4a8e-89e9-6
                    first_name: Anshul
                    last_name: Rajput
                    email: anshulrajput229@gmail.com
                  joining_date: '2022-07-08T10:41:36.600148Z'
                  role: 1
                owner: 216bba3d-7268-4a8e-89e9-6
                roles:
                - unique_id: 89752b4a-43df-401d-9dc0-a446690a7a0e
                  team: 61010821-08aa-4098-94f8-f88f1990b54a
                  title: Incident Commander
                  description: The incident commander is the person responsible for all aspects of the incident response, including quickly developing incident objectives, managing all incident operations, application of resources as well as responsibility for all persons involved. The incident commander sets priorities and defines the organization of the incident response teams and the overall incident action plan.
                  creation_date: '2022-07-08T10:41:36.623257Z'
                  rank: 1
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
  /api/account/teams/{team_id}/:
    parameters:
    - name: team_id
      in: path
      description: unique_id of the Team object
      schema:
        type: string
      required: true
    get:
      tags:
      - Teams
      summary: Retrieve the Team object
      description: Retrieve the specified Team object.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
              example:
                unique_id: 1f1b4d79-ed32-44fc-926d-f794b975200c
                name: Operation Team
                account: 0713dc12-40b0-46ff-b0f9-c6b126399277
                creation_date: '2022-07-08'
                members:
                - unique_id: 90a97f10-d290-4bd0-9f83-525f130c6399
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  user:
                    username: 216bba3d-7268-4a8e-89e9-6
                    first_name: Anshul
                    last_name: Rajput
                    email: anshulrajput229@gmail.com
                  joining_date: '2022-07-08T10:29:36.408864Z'
                  role: 1
                - unique_id: 4af52265-b69e-4cd0-948a-fba33933588d
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  user:
                    username: 507dfda0-a1fd-40e5-943a-e
                    first_name: Mary
                    last_name: Jane
                    email: maryjane@sharklasers.com
                  joining_date: '2022-07-08T10:31:56.849950Z'
                  role: 2
                - unique_id: 76e76d20-2c82-49be-b987-244c8c6af57b
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  user:
                    username: 85b563c8-18d0-4668-9462-9
                    first_name: Vishwa
                    last_name: Krishnakumar
                    email: vishwa@yellowant.com
                  joining_date: '2022-07-08T10:32:42.213487Z'
                  role: 2
                owner: 216bba3d-7268-4a8e-89e9-6
                roles:
                - unique_id: ce2e4fec-7fb9-440c-b400-9a33639d8ba3
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  title: Incident Commander
                  description: The incident commander is the person responsible for all aspects of the incident response, including quickly developing incident objectives, managing all incident operations, application of resources as well as responsibility for all persons involved. The incident commander sets priorities and defines the organization of the incident response teams and the overall incident action plan.
                  creation_date: '2022-07-08T10:29:36.431801Z'
                  rank: 1
            application/xml:
              schema:
                $ref: '#/components/schemas/Team'
              example:
                unique_id: 1f1b4d79-ed32-44fc-926d-f794b975200c
                name: Operation Team
                account: 0713dc12-40b0-46ff-b0f9-c6b126399277
                creation_date: '2022-07-08'
                members:
                - unique_id: 90a97f10-d290-4bd0-9f83-525f130c6399
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  user:
                    username: 216bba3d-7268-4a8e-89e9-6
                    first_name: Anshul
                    last_name: Rajput
                    email: anshulrajput229@gmail.com
                  joining_date: '2022-07-08T10:29:36.408864Z'
                  role: 1
                - unique_id: 4af52265-b69e-4cd0-948a-fba33933588d
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  user:
                    username: 507dfda0-a1fd-40e5-943a-e
                    first_name: Mary
                    last_name: Jane
                    email: maryjane@sharklasers.com
                  joining_date: '2022-07-08T10:31:56.849950Z'
                  role: 2
                - unique_id: 76e76d20-2c82-49be-b987-244c8c6af57b
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  user:
                    username: 85b563c8-18d0-4668-9462-9
                    first_name: Vishwa
                    last_name: Krishnakumar
                    email: vishwa@yellowant.com
                  joining_date: '2022-07-08T10:32:42.213487Z'
                  role: 2
                owner: 216bba3d-7268-4a8e-89e9-6
                roles:
                - unique_id: ce2e4fec-7fb9-440c-b400-9a33639d8ba3
                  team: 1f1b4d79-ed32-44fc-926d-f794b975200c
                  title: Incident Commander
                  description: The incident commander is the person responsible for all aspects of the incident response, including quickly developing incident objectives, managing all incident operations, application of resources as well as responsibility for all persons involved. The incident commander sets priorities and defines the organization of the incident response teams and the overall incident action plan.
                  creation_date: '2022-07-08T10:29:36.431801Z'
                  rank: 1
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
    put:
      tags:
      - Teams
      summary: Update the Team object
      description: Updates the specified Team object by setting the values of the parameters passed in the request body. Any parameters not provided will be left unchanged.
      requestBody:
        description: Request body parameters to update the Team object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamPayload'
            example:
              name: Modified Production Team
          application/xml:
            schema:
              $ref: '#/components/schemas/TeamPayload'
            example:
              name: Modified Production Team
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
              example:
                unique_id: 61010821-08aa-4098-94f8-f88f1990b54a
                name: Modified Production Team
                account: 0713dc12-40b0-46ff-b0f9-c6b126399277
                creation_date: '2022-07-08'
                members:
                - unique_id: d916157c-ff8b-43be-8e99-4b63699fdf72
                  team: 61010821-08aa-4098-94f8-f88f1990b54a
                  user:
                    username: 216bba3d-7268-4a8e-89e9-6
                    first_name: Anshul
                    last_name: Rajput
                    email: anshulrajput229@gmail.com
                  joining_date: '2022-07-08T10:41:36.600148Z'
                  role: 1
                owner: 216bba3d-7268-4a8e-89e9-6
                roles:
                - unique_id: 89752b4a-43df-401d-9dc0-a446690a7a0e
                  team: 61010821-08aa-4098-94f8-f88f1990b54a
                  title: Incident Commander
                  description: The incident commander is the person responsible for all aspects of the incident response, including quickly developing incident objectives, managing all incident operations, application of resources as well as responsibility for all persons involved. The incident commander sets priorities and defines the organization of the incident response teams and the overall incident action plan.
                  creation_date: '2022-07-08T10:41:36.623257Z'
                  rank: 1
            application/xml:
              schema:
                $ref: '#/components/schemas/Team'
              example:
                unique_id: 61010821-08aa-4098-94f8-f88f1990b54a
                name: Modified Production Team
                account: 0713dc12-40b0-46ff-b0f9-c6b126399277
                creation_date: '2022-07-08'
                members:
                - unique_id: d916157c-ff8b-43be-8e99-4b63699fdf72
                  team: 61010821-08aa-4098-94f8-f88f1990b54a
                  user:
                    username: 216bba3d-7268-4a8e-89e9-6
                    first_name: Anshul
                    last_name: Rajput
                    email: anshulrajput229@gmail.com
                  joining_date: '2022-07-08T10:41:36.600148Z'
                  role: 1
                owner: 216bba3d-7268-4a8e-89e9-6
                roles:
                - unique_id: 89752b4a-43df-401d-9dc0-a446690a7a0e
                  team: 61010821-08aa-4098-94f8-f88f1990b54a
                  title: Incident Commander
                  description: The incident commander is the person responsible for all aspects of the incident response, including quickly developing incident objectives, managing all incident operations, application of resources as well as responsibility for all persons involved. The incident commander sets priorities and defines the organization of the incident response teams and the overall incident action plan.
                  creation_date: '2022-07-08T10:41:36.623257Z'
                  rank: 1
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
    delete:
      tags:
      - Teams
      summary: Delete the Team object
      description: Delete the specified Team object permanently.
      responses:
        '204':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
components:
  schemas:
    User:
      type: object
      description: User object schema
      properties:
        username:
          type: string
          description: A system-generated string that represents the User object's username
        first_name:
          type: string
          description: A string that represents the User object's first_name
        last_name:
          type: string
          description: A string that represents the User object's last_name
        email:
          type: string
          description: A string that represents the User object's email
    TeamMember:
      type: object
      description: Team Member object schema
      properties:
        unique_id:
          type: string
          description: A system-generated string that represents the Team Member object's unique_id
        team:
          type: string
          description: A system-generated string that represents the Team object's unique_id
        user:
          $ref: '#/components/schemas/User'
        joining_date:
          type: string
          format: datetime
          description: A formatted string that represents the Team Member object's joining_date
        role:
          type: integer
          default: 2
          description: An integer that represents the Team Member object's role. 1 is manager and 2 is user
    TeamPayload:
      type: object
      description: Payload schema for the Team object
      required:
      - name
      properties:
        name:
          type: string
          description: A that represents the Team object's name
    IncidentRoleGet:
      type: object
      description: Incident Role object schema
      properties:
        unique_id:
          type: string
          description: A system-generated string that represents the Incident Role object's unique_id
        team:
          type: string
          description: A system-generated string that represents the Team object's unique_id
        title:
          type: string
          description: An arbitary string that represents the Incident Role object's title
        description:
          type: string
          description: An arbitary string that represents the Incident Role object's description
        creation_date:
          type: string
          format: date-time
          description: A formatted string that represents the Incident Role object's creation_date
        rank:
          type: integer
          default: 1
          description: An integer that represents the Incident Role object's rank
    Team:
      type: object
      description: Team object schema
      properties:
        unique_id:
          type: string
          description: A system-generated string that represents the Team object's unique_id
        name:
          type: string
          description: A that represents the Team object's name
        account:
          type: string
          description: A system-generated string that represents the Account object's unique_id
        creation_date:
          type: string
          format: date-time
          description: A formatted string that represents the Team object's creation_date
        members:
          $ref: '#/components/schemas/TeamMember'
        owner:
          type: string
          description: A system-generated string that represents the User object's username
        roles:
          $ref: '#/components/schemas/IncidentRoleGet'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Token <api_key>
