openapi: 3.0.0
info:
  version: 1.1.0
  title: Zenduty Account Custom Role Postmortem API
  termsOfService: https://zenduty.com
  contact:
    email: vishwa@zenduty.com
  license:
    name: Apache 2.0
  x-logo:
    url: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOS4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9Ii05OC4zIDE3My43IDIwNi4zIDUzLjIiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgLTk4LjMgMTczLjcgMjA2LjMgNTMuMjsiIHhtbDpzcGFjZT0icHJlc2VydmUiPg0KPHN0eWxlIHR5cGU9InRleHQvY3NzIj4NCgkuc3Qwe2ZpbGw6IzBGMTcyQTt9DQoJLnN0MXtmaWxsOiNGRDlBMDA7fQ0KPC9zdHlsZT4NCjxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0tMjksMjEwLjJoNi4zYzIuNywwLDQuOSwyLjIsNC45LDQuOWgtMTguMWMwLTUuMyw0LjEtOS40LDcuOS0xMy4xbDMuOC0zLjdoLTcuMWMtMi41LDAtNC42LTIuMS00LjYtNC42aDE4DQoJYzAsNS4zLTQuMSw5LjQtNy44LDEzLjJMLTI5LDIxMC4yeiIvPg0KPHBhdGggY2xhc3M9InN0MCIgZD0iTTMuNywyMDUuOGgtMTUuNWMwLjEsMS41LDAuNiwyLjcsMS42LDMuNmMwLjksMC45LDIuMSwxLjIsMy41LDEuMmMyLDAsMy40LTAuOSw0LjMtMi41aDUuOA0KCWMtMC42LDItMS44LDMuNi0zLjUsNC45Yy0xLjgsMS4yLTMuOSwyLTYuNCwyYy0yLDAtMy45LTAuNS01LjUtMS40Yy0xLjYtMC45LTIuOS0yLjEtMy44LTMuN2MtMC45LTEuNi0xLjQtMy40LTEuNC01LjcNCgljMC0yLjEsMC41LTQuMSwxLjQtNS43YzAuOS0xLjYsMi4xLTIuOCwzLjgtMy43YzEuNi0wLjksMy40LTEuNCw1LjUtMS40YzIsMCwzLjgsMC40LDUuNCwxLjJjMS42LDAuOSwyLjgsMi4xLDMuNywzLjYNCgljMC45LDEuNiwxLjMsMy4zLDEuMyw1LjRDMy44LDIwNC42LDMuOCwyMDUuMiwzLjcsMjA1Ljh6IE0tMS43LDIwMi4yYzAtMS40LTAuNS0yLjUtMS41LTMuMmMtMS0wLjktMi4xLTEuMi0zLjUtMS4yDQoJYy0xLjQsMC0yLjQsMC40LTMuNCwxLjJjLTAuOSwwLjctMS41LDEuOC0xLjYsMy4zaDEwLjFWMjAyLjJ6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNMjcuOSwxOTguNGMwLjktMS42LDItMi45LDMuNS0zLjhjMS41LTAuOSwzLjEtMS40LDQuOS0xLjRjMS40LDAsMi42LDAuMywzLjksMC45YzEuMywwLjYsMi4zLDEuNCwzLDIuNHYtMTYuNw0KCWg1LjR2MzVoLTUuNHYtMy4xYy0wLjYsMS0xLjYsMS45LTIuOCwyLjVjLTEuMywwLjYtMi42LDEtNC4yLDFjLTEuOCwwLTMuNC0wLjUtNC45LTEuNGMtMS41LTAuOS0yLjYtMi4zLTMuNS0zLjkNCgljLTAuOS0xLjYtMS4zLTMuNS0xLjMtNS44QzI2LjYsMjAyLDI3LDIwMCwyNy45LDE5OC40eiBNNDIuNSwyMDAuOWMtMC41LTAuOS0xLjMtMS42LTItMi4xYy0wLjktMC41LTEuOC0wLjgtMi44LTAuOA0KCWMtMSwwLTEuOSwwLjMtMi44LDAuOGMtMC45LDAuNS0xLjUsMS4xLTIsMi4xYy0wLjUsMC45LTAuOCwyLTAuOCwzLjNjMCwxLjMsMC4zLDIuNCwwLjgsMy40YzAuNSwxLDEuMywxLjYsMiwyLjENCgljMC45LDAuNSwxLjgsMC44LDIuOCwwLjhjMSwwLDEuOS0wLjMsMi44LTAuOGMwLjktMC41LDEuNS0xLjMsMi0yLjFjMC41LTAuOSwwLjgtMiwwLjgtMy40UzQzLDIwMS44LDQyLjUsMjAwLjl6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNMjUuNCwyMDQuM3YxMC42aC01di0xMC42YzAtMi0wLjUtMy41LTEuNS00LjVjLTEtMS4xLTIuMS0xLjYtMy41LTEuNnMtMi41LDAuNS0zLjUsMS42DQoJYy0wLjksMS0xLjQsMi42LTEuNCw0LjV2MTAuNkg1LjV2LTEwLjZjMC0yLjEsMC41LTQsMS4zLTUuN2MwLjktMS42LDItMi45LDMuNS0zLjhzMy4xLTEuNCw1LTEuNHMzLjUsMC41LDUsMS40DQoJYzEuNSwwLjksMi42LDIuMSwzLjUsMy44QzI0LjksMjAwLjMsMjUuNCwyMDIuMiwyNS40LDIwNC4zeiIvPg0KPHBhdGggY2xhc3M9InN0MCIgZD0iTTUxLjMsMjA0LjF2LTEwLjRoNXYxMC40YzAsMiwwLjUsMy41LDEuNSw0LjVjMSwxLjEsMi4xLDEuNiwzLjUsMS42YzEuNCwwLDIuNS0wLjUsMy41LTEuNg0KCWMwLjktMSwxLjQtMi42LDEuNC00LjV2LTEwLjRoNC45djEwLjRjMCwyLjEtMC41LDQtMS4zLDUuN2MtMC45LDEuNi0yLDIuOS0zLjUsMy44Yy0xLjUsMC45LTMuMSwxLjQtNSwxLjRzLTMuNS0wLjUtNS0xLjQNCgljLTEuNS0wLjktMi42LTIuMS0zLjUtMy44QzUxLjcsMjA4LjEsNTEuMywyMDYuMiw1MS4zLDIwNC4xeiIvPg0KPHBhdGggY2xhc3M9InN0MCIgZD0iTTgwLjcsMTk4djEwLjJjMCwwLjgsMC4xLDEuMywwLjUsMS41YzAuNCwwLjQsMC45LDAuNSwxLjgsMC41aDIuNXY0LjVoLTMuNGMtNC41LDAtNi44LTIuMS02LjgtNi41VjE5OGgtNS4xDQoJdi00LjRoNS4xdi04LjdoNS40djguN2g0LjhsMi42LDQuNEg4MC43eiIvPg0KPHBhdGggY2xhc3M9InN0MCIgZD0iTTEwNy40LDE5My42bC04LjcsMjAuNmwtNSwxMS44aC01LjdsNS4xLTExLjhsLTguNC0yMC42aDZsNS40LDE0LjdsNS41LTE0LjdIMTA3LjR6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNLTY2LjksMTg5LjJjLTEuOSwwLTQuNy0yLjEtNC43LTQuOHYtMy42YzAtMi43LDAuOC00LjgsNC43LTQuOGMzLjksMCw0LjcsMi4xLDQuNyw0Ljh2My42DQoJQy02Mi4yLDE4Ny4xLTY1LDE4OS4yLTY2LjksMTg5LjJ6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNLTM3LjcsMjIzaC0yMS41bDMuOC0xMS40bDAuNy0xLjhjNC4yLDEuNywxMy4xLDcuMiwxNy43LDExLjZDLTM2LjQsMjIyLjEtMzYuOCwyMjMtMzcuNywyMjN6Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNLTU3LjMsMTkyLjlsLTE1LjksMTAuNGMtNC4yLTIuNS05LjItNS45LTEyLjItOC44Yy0wLjYtMC42LTAuMi0xLjUsMC43LTEuNUgtNTcuM3oiLz4NCjxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik0tNDguNiwxOTQuM2wtNiwxNS42bC0wLjcsMS44bC0zLjgsMTEuNEgtOTZjLTAuOCwwLTEuMy0wLjktMC44LTEuNWMwLjktMS4yLDEuOC0yLjMsMi43LTMuMw0KCWMyLjEtMi4yLDQuNC00LjEsNi45LTUuOGwwLjEtMC4xYzAuOC0wLjYsMS42LTEuMSwyLjQtMS42bDExLjQtNy40bDE1LjktMTAuNGg3LjdDLTQ4LjgsMTkyLjktNDguNCwxOTMuNi00OC42LDE5NC4zeiIvPg0KPC9zdmc+DQo=
  description: "# Introduction\n\nZenduty is a cutting edge platform for incident management. With high level automation, Zenduty enables faster and better incident resolution keeping developers first.\n\n\n  Javascript Libraries: https://github.com/Zenduty/zenduty-js\n\n  Ruby Libraries: https://github.com/Zenduty/zenduty-ruby\n\n  Python Libraries: https://github.com/Zenduty/zenduty-python-sdk\n\n  Postman Collection for Zenduty API: https://github.com/Zenduty/zenduty-api-postman.git\n\n  Account-level roles and permissions: https://docs.zenduty.com/docs/users#account-level-roles-and-permissions\n\n  Team-level roles and permissions: https://docs.zenduty.com/docs/users#team-level-roles-and-permissions\n"
servers:
- url: https://www.zenduty.com
security:
- bearerAuth: []
tags:
- name: Postmortem
  description: This object represents the postmortem of an incident. You can checkout the postmortem docs here https://docs.zenduty.com/docs/incidentpostmortem
paths:
  /api/account/teams/{}/postmortem/:
    parameters:
    - name: team_id
      in: path
      description: unique_id of the Team object
      schema:
        type: string
      required: true
    post:
      tags:
      - Postmortem
      summary: Create the Postmortem object
      description: Create the Postmortem object by setting the values of all the required parameters passed in the request body.
      requestBody:
        description: Request body parameters to create the Postmortem object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostmortemPayload'
            example:
              author: 85b563c8-18d0-4668-9462-9
              incidents:
              - incident: U2gGkyJnLQLkX2zQnvkpLW
              title: New Infra Postmortem
          application/xml:
            schema:
              $ref: '#/components/schemas/PostmortemPayload'
            example:
              author: 85b563c8-18d0-4668-9462-9
              incidents:
              - incident: U2gGkyJnLQLkX2zQnvkpLW
              title: New Infra Postmortem
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostmortemPostPut'
              example:
                unique_id: f6778c71-eba2-49da-b226-ca27172d7303
                author: 85b563c8-18d0-4668-9462-9
                status: ''
                incidents:
                - unique_id: 80673be0-aa18-4f70-ae92-dec403dfc32e
                  incident: U2gGkyJnLQLkX2zQnvkpLW
                author_name: Vishwa Krishnakumar
                title: New Infra Postmortem
                postmortem_data: ''
                download_status: 0
            application/xml:
              schema:
                $ref: '#/components/schemas/PostmortemPostPut'
              example:
                unique_id: f6778c71-eba2-49da-b226-ca27172d7303
                author: 85b563c8-18d0-4668-9462-9
                status: ''
                incidents:
                - unique_id: 80673be0-aa18-4f70-ae92-dec403dfc32e
                  incident: U2gGkyJnLQLkX2zQnvkpLW
                author_name: Vishwa Krishnakumar
                title: New Infra Postmortem
                postmortem_data: ''
                download_status: 0
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
    get:
      tags:
      - Postmortem
      summary: List all Postmortem objects
      description: Returns a list of Postmortem objects.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostmortemGet'
              example:
              - unique_id: 4d0726ca-664f-4d07-8005-a9ba2c654cc9
                author: 85b563c8-18d0-4668-9462-9
                status: Critical
                postmortem_data: <p>This is the Infra Postmortem data</p>
                incidents:
                - unique_id: d86daf72-a2f2-4d54-adec-19f4380ada48
                  incident:
                    unique_id: U2gGkyJnLQLkX2zQnvkpLW
                    title: Infra Incident
                    incident_number: 1
                author_name: Vishwa Krishnakumar
                title: Infra Postmortem
                download_status: 1
                amazon_link: https://zenduty-dev-report.s3.amazonaws.com/
                creation_date: '2022-07-08T12:35:38.234310Z'
              - unique_id: f6778c71-eba2-49da-b226-ca27172d7303
                author: 85b563c8-18d0-4668-9462-9
                status: ''
                postmortem_data: ''
                incidents:
                - unique_id: 80673be0-aa18-4f70-ae92-dec403dfc32e
                  incident:
                    unique_id: U2gGkyJnLQLkX2zQnvkpLW
                    title: Infra Incident
                    incident_number: 1
                author_name: Vishwa Krishnakumar
                title: New Infra Postmortem
                download_status: 0
                amazon_link: https://zenduty-dev-report.s3.amazonaws.com/
                creation_date: '2022-07-08T15:08:01.521494Z'
            application/xml:
              schema:
                $ref: '#/components/schemas/PostmortemGet'
              example:
              - unique_id: 4d0726ca-664f-4d07-8005-a9ba2c654cc9
                author: 85b563c8-18d0-4668-9462-9
                status: Critical
                postmortem_data: <p>This is the Infra Postmortem data</p>
                incidents:
                - unique_id: d86daf72-a2f2-4d54-adec-19f4380ada48
                  incident:
                    unique_id: U2gGkyJnLQLkX2zQnvkpLW
                    title: Infra Incident
                    incident_number: 1
                author_name: Vishwa Krishnakumar
                title: Infra Postmortem
                download_status: 1
                amazon_link: https://zenduty-dev-report.s3.amazonaws.com/
                creation_date: '2022-07-08T12:35:38.234310Z'
              - unique_id: f6778c71-eba2-49da-b226-ca27172d7303
                author: 85b563c8-18d0-4668-9462-9
                status: ''
                postmortem_data: ''
                incidents:
                - unique_id: 80673be0-aa18-4f70-ae92-dec403dfc32e
                  incident:
                    unique_id: U2gGkyJnLQLkX2zQnvkpLW
                    title: Infra Incident
                    incident_number: 1
                author_name: Vishwa Krishnakumar
                title: New Infra Postmortem
                download_status: 0
                amazon_link: https://zenduty-dev-report.s3.amazonaws.com/
                creation_date: '2022-07-08T15:08:01.521494Z'
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
  /api/account/teams/{team_id}/postmortem/{postmortem_id}/:
    parameters:
    - name: team_id
      in: path
      description: unique_id of the Team object
      schema:
        type: string
      required: true
    - name: postmortem_id
      in: path
      description: unique_id of the Postmortem object
      schema:
        type: string
      required: true
    get:
      tags:
      - Postmortem
      summary: Retrieve the Postmortem object
      description: Retrieve the specified Postmortem object.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostmortemGet'
              example:
                unique_id: f6778c71-eba2-49da-b226-ca27172d7303
                author: 85b563c8-18d0-4668-9462-9
                status: ''
                postmortem_data: ''
                incidents:
                - unique_id: 80673be0-aa18-4f70-ae92-dec403dfc32e
                  incident:
                    unique_id: U2gGkyJnLQLkX2zQnvkpLW
                    title: Infra Incident
                    incident_number: 1
                author_name: Vishwa Krishnakumar
                title: New Infra Postmortem
                download_status: 0
                amazon_link: https://zenduty-dev-report.s3.amazonaws.com/
                creation_date: '2022-07-08T15:08:01.521494Z'
            application/xml:
              schema:
                $ref: '#/components/schemas/PostmortemGet'
              example:
                unique_id: f6778c71-eba2-49da-b226-ca27172d7303
                author: 85b563c8-18d0-4668-9462-9
                status: ''
                postmortem_data: ''
                incidents:
                - unique_id: 80673be0-aa18-4f70-ae92-dec403dfc32e
                  incident:
                    unique_id: U2gGkyJnLQLkX2zQnvkpLW
                    title: Infra Incident
                    incident_number: 1
                author_name: Vishwa Krishnakumar
                title: New Infra Postmortem
                download_status: 0
                amazon_link: https://zenduty-dev-report.s3.amazonaws.com/
                creation_date: '2022-07-08T15:08:01.521494Z'
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
    put:
      tags:
      - Postmortem
      summary: Update the Postmortem data
      description: Updates the specified Postmortem object by setting the values of the parameters passed in the request body. Any parameters not provided will be left unchanged.
      requestBody:
        description: Request body parameters to update the Postmortem object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostmortemPayload'
            example:
              author: 85b563c8-18d0-4668-9462-9
              incidents:
              - incident: U2gGkyJnLQLkX2zQnvkpLW
              title: Modified Infra Postmortem
          application/xml:
            schema:
              $ref: '#/components/schemas/PostmortemPayload'
            example:
              author: 85b563c8-18d0-4668-9462-9
              incidents:
              - incident: U2gGkyJnLQLkX2zQnvkpLW
              title: Modified Infra Postmortem
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostmortemPostPut'
              example:
                unique_id: f6778c71-eba2-49da-b226-ca27172d7303
                author: 85b563c8-18d0-4668-9462-9
                status: null
                incidents:
                - unique_id: 80673be0-aa18-4f70-ae92-dec403dfc32e
                  incident: U2gGkyJnLQLkX2zQnvkpLW
                author_name: Vishwa Krishnakumar
                title: Modified Infra Postmortem
                postmortem_data: null
                download_status: 0
            application/xml:
              schema:
                $ref: '#/components/schemas/PostmortemPostPut'
              example:
                unique_id: f6778c71-eba2-49da-b226-ca27172d7303
                author: 85b563c8-18d0-4668-9462-9
                status: null
                incidents:
                - unique_id: 80673be0-aa18-4f70-ae92-dec403dfc32e
                  incident: U2gGkyJnLQLkX2zQnvkpLW
                author_name: Vishwa Krishnakumar
                title: Modified Infra Postmortem
                postmortem_data: null
                download_status: 0
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
    delete:
      tags:
      - Postmortem
      summary: Delete the Postmortem data
      description: Delete the specified Postmortem object permanently.
      responses:
        '204':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail: This request can not be processed.
            application/xml:
              example:
                detail: This request can not be processed.
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail: You do not have permission to perform this action.
            application/xml:
              example:
                detail: You do not have permission to perform this action.
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail: Not Found.
            application/xml:
              example:
                detail: Not Found.
components:
  schemas:
    PostmortemPostPut:
      type: object
      description: Postmortem object schema
      properties:
        unique_id:
          type: string
          description: A system-generated string that represents the Postmortem object's unique_id
        author:
          type: string
          description: A system-generated string that represents the User object's username
        status:
          type: string
          description: A string that represents the Postmortem object's status
        incidents:
          type: array
          description: An array of Postmortem Incident objects
          items:
            type: object
            description: Postmortem Incident object schema
            properties:
              unique_id:
                type: string
                description: A system-generated string that represents the Postmortem Incident object's unique_id
              incident:
                type: string
                description: A system-generated string that represents the Incident object's unique_id
        author_name:
          type: string
          description: A string that represents the User object's full name
        title:
          type: string
          description: A string that represents the Postmortem object's title
        postmortem_data:
          type: string
          description: A string that represents the Postmortem object's postmortem_data
        download_status:
          type: integer
          default: 0
          description: An integer that represents the Postmortem object's download_status. 1 is uninitiated, 2 is initiated, 3 is finished and 4 is error
    PostmortemGet:
      type: object
      description: Postmortem object schema
      properties:
        unique_id:
          type: string
          description: A system-generated string that represents the Postmortem object's unique_id
        author:
          type: string
          description: A system-generated string that represents the User object's username
        status:
          type: string
          description: A string that represents the Postmortem object's status
        postmortem_data:
          type: string
          description: A string that represents the Postmortem object's postmortem_data
        incidents:
          type: array
          description: An array of Postmortem Incident objects
          items:
            type: object
            description: Postmortem Incident object schema
            properties:
              unique_id:
                type: string
                description: A system-generated string that represents the Postmortem Incident object's unique_id
              incident:
                type: object
                description: Incident object schema for a Postmortem object schema
                properties:
                  unique_id:
                    type: string
                    description: A system-generated string that represents the Incident object's unique_id
                  title:
                    type: string
                    description: A string that represents the Incident object's title
                  incident_number:
                    type: integer
                    description: An integer that represents the Incident object's incident_number
        author_name:
          type: string
          description: A string that represents the User object's full name
        title:
          type: string
          description: A string that represents the Postmortem object's title
        download_status:
          type: integer
          default: 0
          description: An integer that represents the Postmortem object's download_status. 1 is uninitiated, 2 is initiated, 3 is finished and 4 is error
        amazon_link:
          type: string
          description: An hyperlink string to AWS
        creation_date:
          type: string
          format: date-time
          description: A formatted string that represents the Postmortem object's creation_date
    PostmortemPayload:
      type: object
      description: Payload schema for the Postmortem object
      required:
      - author
      - incidents
      properties:
        author:
          type: string
          description: A system-generated string that represents the User object's username
        status:
          type: string
          description: A string that represents the Postmortem object's status
        postmortem_data:
          type: string
          description: A string that represents the Postmortem object's postmortem_data
        incidents:
          type: array
          description: An array of Postmortem Incident objects
          items:
            type: object
            description: Postmortem Incident object schema
            properties:
              incident:
                type: object
                description: Incident object schema for a Postmortem object schema
                properties:
                  unique_id:
                    type: string
                    description: A system-generated string that represents the Incident object's unique_id
                  title:
                    type: string
                    description: A string that represents the Incident object's title
                  incident_number:
                    type: integer
                    description: An integer that represents the Incident object's incident_number
        title:
          type: string
          description: A string that represents the Postmortem object's title
        download_status:
          type: integer
          default: 0
          description: An integer that represents the Postmortem object's download_status. 1 is uninitiated, 2 is initiated, 3 is finished and 4 is error
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Token <api_key>
